### ISSUE TITLE
Refactor init script into smaller pieces

### ISSUE THREAD

**Issue by thedeeno** [SebastianWendel/chef-elasticsearch#14]
The init script is large and complex so it's hard figure out how it does it's job. It could be simplified if the platform specific code was abstracted into separate startup scripts and then included via an attribute.

EDIT: typos

**Comment by SebastianWendel** [comment]
There is no need for a refactoring, this script in somehow identical to the upstream package:

https://github.com/elasticsearch/elasticsearch-servicewrapper

Do you have problems else then understanding what's happening?

**Comment by thedeeno** [comment]
Haven't tried this cookbook yet, but if it's the same as upstream I can't complain. Yes, my only complaint was not being able to grok it fast. As you saw, there's tons of platform specific code in it (>1000 lines!?!). Thanks for checking into it.
